### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by sjaehn** [OpenMusicKontrollers/lv2lint#1]
Hi,
if I call lv2lint  as described in README.md (using the option -o), I get:

lv2lint: invalid option -- 'o'
Unknown option `-o'.

As "-o" is not listed in lv2lint -h (and thus probably not supported anymore ?), it can be removed from the README.md to prevent confusion.

**Comment by ventosus** [comment]
Thanks for reporting.

Option -o only is available if online tests have been built-in.

As by default, the build flag is disabled, it indeed makes sense to not mention it in the README.

**Comment by ventosus** [comment]
fixed in db90bed8a51b8193ed08d25b90a6234efb943252
