### ISSUE TITLE
Output relating to http://spdx.org/rdf/terms#License?

### ISSUE THREAD

**Issue by mxmilkiib** [OpenMusicKontrollers/lv2lint#11]
The SPDX ontology seems sound to describe [specific licenses](https://spdx.org/rdf/terms/#d4e2374).

There is the example on https://en.wikipedia.org/wiki/LV2#RDF

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/16>
