### ISSUE TITLE
UI Instantiation failed to instantiate

### ISSUE THREAD

**Issue by brummer10** [OpenMusicKontrollers/lv2lint#12]
In all of my plugs I get recently this warning:
```
[FAIL]  UI Instantiation
              failed to instantiate
              seeAlso: <http://lv2plug.in/ns/extensions/ui#X11UI>
```
while my plugs itself print the following warning:
`ERROR: Failed to open parentXwindow`

So, yes,  
```
if (!strcmp(features[i]->URI, LV2_UI__parent)) {
            ui->parentXwindow = features[i]->data;
}
```
fail, my plugs don't create the UI and return NULL, intentional, as they need a parent widget to be embedded in. 

using lv2lint.bin 0.17.61

**Comment by ventosus** [comment]
migrated to own forge at <https://todo.open-music-kontrollers.ch/~hp/issues/2>
