### ISSUE TITLE
Odd FAIL messages

### ISSUE THREAD

**Issue by sjaehn** [OpenMusicKontrollers/lv2lint#3]
I get frequently informed by @dvzrv about lv2lint (0.2.0) error messages in my lv2 plugins which I can't reproduce using lv2lint and I really don't know why he got them: https://github.com/sjaehn/BSlizr/issues/8#issue-545723151

The odd thing, there are errors about things that clearly are in the lv2 specifications like:
`[FAIL]  Toolkit
              UI toolkit <http://lv2plug.in/ns/extensions/ui#X11UI> unkown
              seeAlso: <http://lv2plug.in/ns/extensions/ui#ui>`

Do you have an idea why this happens?

**Comment by ventosus** [comment]
As commented on  sjaehn/BSlizr#8 i cannot reproduce either.

Most probably a borked LV2 installation, or wrong LV2_PATH, etc.

**Comment by sjaehn** [comment]
Thank you. I suspected the same.
