### ISSUE TITLE
MacOS Support, CocoaUI

### ISSUE THREAD

**Issue by x42** [OpenMusicKontrollers/lv2lint#5]
Testing some plugins on MacOS, I get
```
    [FAIL]  Toolkit
              UI toolkit <http://lv2plug.in/ns/extensions/ui#CocoaUI> unkown
              seeAlso: <http://lv2plug.in/ns/extensions/ui#ui>
```

**Comment by x42** [comment]
PS since MacOS does not come with python3, and meson isn't an option, I wrote a simple makefile:

```make
VERSION=`cat $VERSION`
CFLAGS=`pkg-config --cflags libcurl lv2 lilv-0` -I. -I mapper.lv2 -DLV2LINT_VERSION="\"$(VERSION)\""
LDLIBS=`pkg-config --libs libcurl lv2 lilv-0`
lv2lint: lv2lint.c lv2lint_plugin.c lv2lint_port.c lv2lint_parameter.c lv2lint_ui.c  
```

**Comment by ventosus** [comment]
Thanks for reporting.

I have no access to MacOS hardware, so cannot really test this properly, sorry.

ui#CocoaUI should be detected as native UI with help of preprocessor define __APPLE__ [1].

Is the define set by your compiler at all?

If not, try adding it manually to the CFLAGS, e.g. -D__APPLE__.

Maybe I'm using the wrong define to discover MacOS in the first place...

[1] https://github.com/OpenMusicKontrollers/lv2lint/blob/master/lv2lint_ui.c#L396

**Comment by ventosus** [comment]
As discussed on IRC:

If the LV2 spec is not installed at all or LV2_PATH is invalid (or does not include the spec), lv2lint (via lilblilv) cannot find any definitions.

lv2lint best is only run after a successful {lv2,sord}_validate to prevent such spurious issues.
