### ISSUE TITLE
Duplicate properties?

### ISSUE THREAD

**Issue by mxmilkb** [OpenMusicKontrollers/lv2lint#6]
Like in https://github.com/moddevices/mod-cv-plugins/blob/master/source/mod-cv-clock-divider/mod-cv-clock-divider.lv2/mod-cv-clock-divider.ttl

**Comment by ventosus** [comment]
That's valid Turtle, I'm afraid. nothing wrong about it (apart from being a stupidity).

And nothing that could be discovered by lv2lint, it does not parse Turtle itself.

It relies on lilv [1] and serd [2] which would need to propagate that somehow.

[1] http://drobilla.net/software/lilv
[2] http://drobilla.net/software/serd

**Comment by ventosus** [comment]
Correction: it is invalid Turtle and is also reported so with {sord/lv2}_validate:

    --- stderr ---
    error: Functional property with 2 objects

As the lv2lint is only ever run after passing {lv2/sord}_validate. All is fine.
