### ISSUE TITLE
exclude experimental::filesystem from the binary export scan

### ISSUE THREAD

**Issue by baconpaul** [OpenMusicKontrollers/lv2lint#7]
Hi!

over https://github.com/surge-synthesizer/surge/issues/1698 @falktx @dvzrv and I were chatting about how using experimental::filesystem on linux (and doing the associated -lstdc++fs) means that the std::experimental::filesystem symbols are pushed into a dll no matter how much you strip and so forth.

This means your lv2lint program finds and flags those symbols as improper export

I was wondering if you would consider adding the filesystem symbols to your exclude list. It's a bit tricky since your symbol whitelist is exact match now and you would need to both do a C++-unmangle and then do a partial match or starts with match but didn't want to not flag it to your attention.

Thanks so much!

**Comment by ventosus** [comment]
Thanks for reporting.

Instead of hard-coding this into the built-in minimal list, adding support for whitelisting on the command line sounds like a better option (it has been requested before).

**Comment by baconpaul** [comment]
Sure!

Or even better if we could put a tag in our LV2 metadata saying we export it and you could read that (but I'm not an LV2 expert so don't know if that is possible). That way we could avoid folks making reports that we mis-export when they use the tool without the command line.

**Comment by ventosus** [comment]
support for whitelisting of (wrongly) visible symbols has been added in 5ca6f2410966711672ad72e28321198ffa706581

example usage (shell wildcards are allowed, e.g. * and ?)

    lv2lint -Ewarn -W '*experimental*filesystem*' https://surge-synthesizer.github.io/lv2/surge

Please test and report back if (un)happy :-)

**Comment by baconpaul** [comment]
Yes that did work! Thank you.
