### ISSUE TITLE
lv2:enumeration with redundant lv2:scalePoints ?

### ISSUE THREAD

**Issue by sjaehn** [OpenMusicKontrollers/lv2lint#8]
I just found a bug in one of my plugins .ttl files that passed lv2lint before. I'm not sure if lv2lint should report it or not. It was a bug in lv2:enumeration. Two different lv2:scalePoints with the same value. See https://github.com/sjaehn/BJumblr/blob/4f906ea47467637a6e115435784dc34f6bf63ca7/BJumblr.ttl#L90. I think this isn't incompatible with the lv2 specs, but it doesn't make sense and only causes problems (as I experienced). I know, enums with redundant values are allowed in many programming languages and I even used this, but I think it doesn't make any sense here. Should or shouldn't lv2lint warn about it? What do you think about it ?

**Comment by ventosus** [comment]
Thanks for reporting.

Indeed, such a test would make sense, we should at least generate a WARNING that something  may be wrong.

**Comment by ventosus** [comment]
fixed in c58670a053c7328d2604376b72782e4b4fbb915a, feel free to test

**Comment by sjaehn** [comment]
Thanks, but now please also check for LV2 version 1.18.0  in https://github.com/OpenMusicKontrollers/lv2lint/blob/master/meson.build#L20 as freePath requires this version.

**Comment by ventosus** [comment]
devs should always use latest LV2, imho

fixed 283c337beaa3b23a4479582c603b98817345c58e, thanks

**Comment by ventosus** [comment]
devs should always use lates LV2, imho.

fixed in 283c337beaa3b23a4479582c603b98817345c58e, thankgs
