### ISSUE TITLE
Duplicate port not detected

### ISSUE THREAD

**Issue by jpcima** [OpenMusicKontrollers/lv2lint#9]
Hi, the sfizz plugin mistakenly had the same port entry duplicated twice, and lv2lint is not able to detect this error.

Relevant
https://github.com/sfztools/sfizz/commit/b92209de7468e5cddf70fe9b986087293f852170#r43002462

**Comment by ventosus** [comment]
thanks for reporting.

This is out-of-scope for lv2lint, port discovery is done by liblilv [1], I don't want to copy its code. If you want duplicate ports to be detected somehow, please file the request there, that's the more appropriate place.

[1] http://drobilla.net/software/lilv
